buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.1' // Use latest stable version
    }
}

plugins {
    id 'com.android.library'
}

group 'sq.flutter.tflite'
version '1.0-SNAPSHOT'

android {
    namespace 'sq.flutter.tflite' // Required for Gradle 8+
    compileSdk 34

    defaultConfig {
        minSdk 21
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    lint {
        checkReleaseBuilds false
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation 'org.tensorflow:tensorflow-lite:2.13.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.13.0'
}
